[package]
name = "task1"
version = "1.0.0"
authors = []

[addresses]
hello_world="0x1aa098ae614b2a6dcca43797d1fe132c0a3dec0c50f7125ae8e611abbbd03a83"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "testnet"
subdir = "aptos-framework"

[dev-dependencies]
